project: #项目列表
- name: project1 #项目名
  worker_dir: D:\www\project1 #项目目录
  exec_command: release.bat #发布项目时部署代码
  timeout: 20 #超时时间
- name: project2
  worker_dir: D:\www\project2
  exec_command: release.bat
  timeout: 20

server: #对应server配置信息
  host: 127.0.0.1
  port: 9530
  allow_ips: #允许请求的ip
  - 127.0.0.1